### PR TITLE
Added 'slidesPerPage' option to support multi-item navigation

### PR DESCRIPTION
**Pull request by makbeta**
Thanks for the great plugin, it works nicely and doesn't break my already flex-styled slides. 
I need some functionality so I added it in, I think others may use it as well.

* Added a new option `slidesPerPage` in case someone wants to show multiple slides per page, this was my use case.
* When circles are created the slide index is added as a data parameter
* When the click event happens, I use `event.currentTarget` for wider cross-browser support and to focus on the desired element. Cast it into a var to gain a bit more efficiency. Refer to the added data parameter to locate the slide index.

### CODE REVIEW

**Comment by tomhrtly** [comment]
Thanks for the feedback and pull request @makbeta!

I'm a little unsure what you meant by your first bullet point regarding the `slidesPerPage` option and what that does. Could you elaborate and possibly share your use case through CodePen? This will help me to better understand so I can update the docs with examples.

Also, you mentioned the changes to the click event for wider cross-browser support, do you know which browsers and version this affects as I will update the compatibility page in the docs accordingly.

**Comment by makbeta** [comment]
@tomhrtly 
I have the code implemented on a site that will go live in a day or two, so I'll send a link to that. 
Here's hopefully a good description of what I was trying to do.
I have 6 boxes that I want to display 3 at a time. Currently, the dot navigation would render 6 dots and when I click on each subsequent dot it will shift slides off by one.
What I needed is have 2 dots on the slider, the first will show me the first 3 boxes and the second one would show the boxes 4-6. So the dots would act like a pager, rather than one-slide navigation.

On the compatibility.
I changed `this` to `event.currentTarget` only in one place, but wanted to just let you know about this as it took me once a long time to figure out the compatibility issue with `this` in the event callback functions. I didn't find any documentation in W3 standards as to what `this` is meant to be for an event callback or anywhere else, so each browser has their own implementation and are free to do so. Most notably IE will return the value of `event.target` for `this` instead of `event.currentTarget`. This mainly applies to elements that look like this `<div class="parent"><span class="child"></span></div>`.  So if my event watcher is set up to watch `.parent` but I click on `.child`, in IE `this` will apply only to the `.child` and not the `.parent`. However, if I just reference the event and reference the standard property `currentTarget` even if I click on a `.child` all browsers will give me the `.parent` in the `event.currentTarget` since I set that up as a target for the event. `even.target` will always return the actual clicked element, not the targeted one. 

In my experience, I find that having `this` especially in a long code is confusing as I have to study the context each time what `this` refers to. So it really slows down the code reading and understanding, especially when I read the code written by others. With arrow functions in ES6 the context on `this` now will require even more thought and study, creating a bit of a slow down in reading and comprehension.  When functions are modular and live in various files then hunting for scope of `this` can take some time. So I try to avoid it at all costs because it improves code readability and reasoning about the code and debugging it is a whole lot easier when code uses the variables passed as arguments to the function.

**Comment by tomhrtly** [comment]
@makbeta 

> I have the code implemented on a site that will go live in a day or two, so I'll send a link to that.

That's great, I look forwarding to seeing your use case.

> Here's hopefully a good description of what I was trying to do.
I have 6 boxes that I want to display 3 at a time. Currently, the dot navigation would render 6 dots and when I click on each subsequent dot it will shift slides off by one.
What I needed is have 2 dots on the slider, the first will show me the first 3 boxes and the second one would show the boxes 4-6. So the dots would act like a pager, rather than one-slide navigation.

I've replicated your branch on my local and I understand your option would be a great addition to the plugin, I'm unsure of the name, I believe that if the option were to be called "slidesToScroll" this would clear up any potential confusion.

I also noticed that when having this option enabled, when clicking on a arrow, the active class is removed from the circles until going to the next set of slides. Is this something you can look into?

I appreciate you clarifying the changes for the event callback function and after researching more online I believe this is a positive change for the plugin. Eventually I may be looking into splitting the source files into multiple files.

Just a one question, is there a reason for adding the $ sign as a prefix for the `$clickedCircle` let? Also please remove the dist files from your PR as these get compiled. Only the source file is needed for PRs. I will clarify this in the PR template.

Also, on a final note, the support you've added for the `picture` tag is great and something I should've thought of before, thanks!

**Comment by makbeta** [comment]
@tomhrtly 
Thanks for testing my code, I didn't look closely at the navigation but you were correct, it was buggy. I updated it to take into the account the new option.  Per your suggestion, I renamed the option to `slidesToScroll` for clarity.  

I also rolled back the commit with compiled files so it doesn't clobber things up. Sorry about that. 

As for the $ before the variable, it's a force of habit. I've adopted a while ago [Drupal coding standard](https://www.drupal.org/docs/develop/standards/javascript/javascript-coding-standards#camelcasing) where all jQuery objects are prefixed with `$`. 

Thoughts on the future. I realized that in my implementation the carousels with multiple items per "page" have only circular navigation but no arrows. I can see that some people may want both of those to forward the same amount of slides, while others will want arrows to forward just one slide. Two options for how many slides to scroll may be the best solution in the future, so there is that degree of flexibility.  Leaving it as is for now, as it serves the immediate needs. 

I also briefly looked at your responsive branch but couldn't quite figure out what your plan was there. I know that I will need to address the mobile solution sooner rather than later.  Instead of working on a fork solo, I think helping extend your vision may be the best option here. So let me know if there is anything I can do to help out there. 

P.S. Thanks for creating this plugin. I coded out the with just pure CSS first and used flexbox display. When I tried adding various JS libraries to animate the elements they all mangled things up pretty badly and I had to fight a myriad of inserted inline styles. Your plugin did the job pretty much out of the box, so thank you for writing and sharing the code.

**Comment by tomhrtly** [comment]
@makbeta 

> Thanks for testing my code, I didn't look closely at the navigation but you were correct, it was buggy. I updated it to take into the account the new option. Per your suggestion, I renamed the option to slidesToScroll for clarity.

No problem, I've created a branch called "options-slides-scrolling", would you be able to change the merge branch to that one and then I can get everything updated on the docs before it gets released into 0.2.1?

> Thoughts on the future. I realized that in my implementation the carousels with multiple items per "page" have only circular navigation but no arrows. I can see that some people may want both of those to forward the same amount of slides, while others will want arrows to forward just one slide. Two options for how many slides to scroll may be the best solution in the future, so there is that degree of flexibility. Leaving it as is for now, as it serves the immediate needs.

That's no problem, much appreciate the additions you have added and I can squash any small bugs I find over the weekend with the new option.

> I also briefly looked at your responsive branch but couldn't quite figure out what your plan was there. I know that I will need to address the mobile solution sooner rather than later. Instead of working on a fork solo, I think helping extend your vision may be the best option here. So let me know if there is anything I can do to help out there.

Eventually the responsive option will be an array that has objects for specific options for set breakpoints, similar to how other carousel plugins work as I believe this is the easiest way for developers to quickly change options at certain breakpoints.

Currently having a little trouble figuring out how to "swap" out the objects that get passed into `self.options` so if you have any feedback or ideas that would be much appreciated.

> P.S. Thanks for creating this plugin. I coded out the with just pure CSS first and used flexbox display. When I tried adding various JS libraries to animate the elements they all mangled things up pretty badly and I had to fight a myriad of inserted inline styles. Your plugin did the job pretty much out of the box, so thank you for writing and sharing the code.

No problem, I'm glad you found the plugin helpful. I started developing it because I struggled to find carousel plugins that use modern technology such as ES6 and Flexbox for my job so I just decided what better way to improve my JS skills then to make one myself. That being said, sometime in the future I will be dropping jQuery as a dependency but I want to get some more features added first.

**Comment by tomhrtly** [comment]
@makbeta I've just realized I can change the base branch myself which I've done. I will merge the pull request over the next day or two unless you have any other commits you wish to make, thanks again for your help!

**Pull request merged**
